name: devkitpro/devkitarm
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build libadvance
        run: make -C ./libadvance
      - name: Build minesweeper
        run: make -C ./minesweeper
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: roms
          path: ./*/*.gba
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./minesweeper/minesweeper.gba
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
