name: devkitarm
on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build libadvance
        run: make -C ./libadvance
      - name: Build minesweeper
        run: make -C ./minesweeper
      - name: Build 2048
        run: make -C ./2048
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: roms
          path: ./*/*.gba
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          files: |
            ./minesweeper/minesweeper.gba
            ./2048/2048.gba
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
