name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build libadvance
        working-directory: ${{runner.workspace}}/libadvance
        run: make
      - name: Build minesweeper
        working-directory: ${{runner.workspace}}/minesweeper
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: roms
          path: ${{runner.workspace}}/*/*.gba
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{runner.workspace}}/minesweeper/minesweeper.gba
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
